# Generated by Django 5.1.6 on 2025-02-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('zonas', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_construccion', models.CharField(choices=[('casa_pequena_1p', 'Casa pequeña de una planta'), ('casa_mediana_1p', 'Casa mediana de una planta'), ('casa_grande_1p', 'Casa grande de una planta'), ('casa_pequena_2p', 'Casa pequeña de 2 plantas'), ('casa_mediana_2p', 'Casa mediana de 2 plantas'), ('casa_grande_2p', 'Casa grande de 2 plantas'), ('casa_3p', 'Casa de 3 plantas'), ('casa_mas_3p', 'Casa de +3 plantas'), ('local_pequeno_1p', 'Local pequeño de 1 planta'), ('local_mediano_1p', 'Local mediano de 1 planta'), ('local_grande_1p', 'Local grande de 1 planta'), ('local_mediano_2p', 'Local mediano de 2 plantas'), ('local_grande_2p', 'Local grande de 2 plantas'), ('local_3p', 'Local de 3 plantas'), ('local_mas_3p', 'Local de +3 plantas'), ('zona_recreativa', 'Zona recreativa'), ('centro_comercial', 'Centro comercial'), ('gasolinera', 'Gasolinera'), ('condominio', 'Condominio'), ('edificio_estado', 'Edificio del estado'), ('espacios_salud', 'Espacios de salud')], max_length=50)),
                ('area_verde', models.BooleanField(default=False)),
                ('servicios_basicos', models.BooleanField(default=False)),
                ('facil_acceso', models.BooleanField(default=False)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='Permisos.municipio')),
            ],
        ),
    ]
