# Generated by Django 5.1.6 on 2025-02-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='zonas',
            field=models.IntegerField(),
        ),
    ]
