# Generated by Django 5.1.6 on 2025-02-09 04:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0002_alter_municipio_zonas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=1000)),
                ('descripcion_proyecto', models.TextField(max_length=2000)),
                ('tipo_proyecto', models.CharField(choices=[('casa_pequena_1p', 'Casa pequeña de una planta'), ('casa_mediana_1p', 'Casa mediana de una planta'), ('casa_grande_1p', 'Casa grande de una planta'), ('casa_pequena_2p', 'Casa pequeña de 2 plantas'), ('casa_mediana_2p', 'Casa mediana de 2 plantas'), ('casa_grande_2p', 'Casa grande de 2 plantas'), ('casa_3p', 'Casa de 3 plantas'), ('casa_mas_3p', 'Casa de +3 plantas'), ('local_pequeno_1p', 'Local pequeño de 1 planta'), ('local_mediano_1p', 'Local mediano de 1 planta'), ('local_grande_1p', 'Local grande de 1 planta'), ('local_mediano_2p', 'Local mediano de 2 plantas'), ('local_grande_2p', 'Local grande de 2 plantas'), ('local_3p', 'Local de 3 plantas'), ('local_mas_3p', 'Local de +3 plantas'), ('zona_recreativa', 'Zona recreativa'), ('centro_comercial', 'Centro comercial'), ('gasolinera', 'Gasolinera'), ('condominio', 'Condominio'), ('edificio_estado', 'Edificio del estado'), ('espacios_salud', 'Espacios de salud')], max_length=50)),
                ('area_verde', models.BooleanField(default=False)),
                ('servicios_basicos', models.BooleanField(default=False)),
                ('facil_acceso', models.BooleanField(default=False)),
                ('responsable', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='ingresado', max_length=10)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Permisos.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('autorizacion', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='rechazado', max_length=10)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Permisos.proyecto')),
            ],
        ),
    ]
