# Generated by Django 5.1.6 on 2025-02-10 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0003_proyecto_autorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre_proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y números.', regex='^[a-zA-Z0-9\\s]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='autorizacion',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Debe ser un email válido.')]),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Permisos.proyecto'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='responsable',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Debe ser un email válido.')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
