# Generated by Django 5.1.6 on 2025-02-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permisos', '0004_remove_proyecto_descripcion_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='plano',
            field=models.ImageField(blank=True, null=True, upload_to='planos'),
        ),
    ]
